line_length: 120

excluded:
  - Carthage
  - SPM
  - .build

opt_in_rules:
  - empty_count
  - anyobject_protocol
  - collection_alignment
  - implicit_return

disabled_rules:
  - type_name
  - identifier_name
  - file_length
  - type_body_length
  - function_parameter_count
